name: "Clang-tidy"

"on":
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

permissions: "read-all"

env:
  LLVM_VERSION: "18"

jobs:
  scan:
    runs-on: ${{ github.repository_owner == 'intel' && 'ubuntu-24.04' || 'innersource.prod.amr.dind' }}
    container:
      image: "ubuntu:24.04"

    steps:
      - name: "Install dependencies and create temp dir"
        working-directory: ${{ env.TEMP_WORKSPACE }}
        run: |
          TEMP_DIR=${{ github.workspace }}/${{ github.run_id }}
          echo "TEMP_WORKSPACE=$TEMP_DIR" >> $GITHUB_ENV
          mkdir -p "$TEMP_DIR" && cd "$TEMP_DIR"

          apt-get update && apt-get install -y git cmake nasm lsb-release wget software-properties-common
          wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && /bin/bash llvm.sh ${{ env.LLVM_VERSION }} all
          ln -s /usr/bin/clang-tidy-${{ env.LLVM_VERSION }} /usr/bin/clang-tidy

      - name: "Checkout repository"
        uses: "actions/checkout@v4"
        with:
          submodules: "true"
          clean: "true"
          path: ${{ env.TEMP_WORKSPACE }}

      - name: "Run clang-tidy scan"
        working-directory: ${{ env.TEMP_WORKSPACE }}
        run: |
          mkdir build && cd build
          export CC=clang-${{ env.LLVM_VERSION }}
          export CXX=clang++-${{ env.LLVM_VERSION }}
          cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release -DQPL_USE_CLANG_TIDY=ON
          cmake --build . --target install --parallel 8

      - name: "Clean up workspace"
        if: always()
        run: |
          rm -rf "$TEMP_WORKSPACE"
